// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using surveyProjectYAS.Models;

#nullable disable

namespace surveyProjectYAS.Migrations
{
    [DbContext(typeof(SurveyContext))]
    [Migration("20250616120804_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.17");

            modelBuilder.Entity("surveyProjectYAS.Models.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VoteCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuestionId = 1,
                            Text = "Kırmızı",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 2,
                            QuestionId = 1,
                            Text = "Mavi",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 3,
                            QuestionId = 1,
                            Text = "Yeşil",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 4,
                            QuestionId = 1,
                            Text = "Sarı",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 5,
                            QuestionId = 1,
                            Text = "Siyah",
                            VoteCount = 0
                        });
                });

            modelBuilder.Entity("surveyProjectYAS.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "En sevdiğiniz renk nedir?"
                        });
                });

            modelBuilder.Entity("surveyProjectYAS.Models.Option", b =>
                {
                    b.HasOne("surveyProjectYAS.Models.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("surveyProjectYAS.Models.Question", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
